dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  chrome: stable
  chromedriver: "./node_modules/protractor/bin/webdriver-manager update --versions.chrome=84.0.4147.30"
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  provider: heroku
  api_key:
    secure: CfR57Wtcy8nXZ6/+ANdPz1d1DR30ic61amEML9nzSQGesoAFlFiagUMbhSDOOTuPHwwrhbfxZvdz7HAW2Ss+wMXFlYWyV6xZxrIjr95fEU+X/CwJLKdCzsYi1aIVJWfeWC+g/l0Ver6u3epgjMYoUv/hwd4Wr+I8s97hOqww476Nj7Z/J0SkhVWWg63vhTgfB7CN9bkYm1ETn914OT4aM3sC3bN8iMSvsXwm6zYrRwclZmbo4ZFcKthkTvSResp8+lzcfytcXASZQpuz7YUdgA74zYPmnyxRmVgKAD8fNk9XEPWcrn/lTlDtF9OYaruz+9sOrE5UrRkYF9Qcy8fftfk2YLJPiG701mj6WimzAKwZ/NhzvLHOzzmRU67TaoF0fHyWBK8800oAJW8MJ2gVmDFHhE1flxHbD52VYJY/ka9M0UYueEVd5hEuPeLNIyfg83nBPFDPSnZtfHXFPOL7M2Ud7RR5HGOo1mLoUfayNbEj3VO7X0YxUWvcagxzTh8F6eG0mo9sj57+4Ep+qCuBH5ePViQJCi/d4JYz+OLkFcVd18zgsMNpeQgZqApZAUwvc4GbzNcuzwSQ4JU5kCoxl6spQO5Z9CJT6s6BY/8EB96hZNXWNA3CHo+I1LAlDluReGZiUtPs9EM0KmyUTsUE/tmbVzs5DjWZTGtUQ0xGX0I=
  app: gdc2Client
  on:
    repo: lightsage88/gdc2Client
  skip_cleanup: 'true'
