dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  chrome: stable
  chromedriver: ./node_modules/protractor/bin/webdriver-manager update --versions.chrome=84.0.4147.30
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  provider: heroku
  api_key:
    secure: 72b5fa63-feab-44ff-9bbe-a89a63393855
  app: fast-brushlands-35777
  on:
    repo: lightsage88/gdc2Client
