dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  chrome: stable
  chromedriver: "./node_modules/protractor/bin/webdriver-manager update --versions.chrome=84.0.4147.30"
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  provider: heroku
  api_key:
    secure: aIcjaBp1ZY33CUoPsSpQQcURrsEzbtzt/XXGFqR9/5W1kmpRoADUC5AWo6NFmr0p+It5PBa9y16kk2idTlT5N+Ei/ZnfXWISlVkdoWBLF0XRPi0GqEJmssRsr7EGkFs9qkBhXn1BU8uPfovm7YvuE+Zb1f5GIxXE/xNYpQIYVgxGDaWhKeBAS16pqNrC49i1+KB40kGAlAyjzjGanndoSpVzq39NVH8g+TcCGWWr9JVIybL+muVbTdjTgYDvfSxHu6+jLMPl9US0KtherR4MYrf9tM69bkxUutnMX7Sga8xs39SG9l6y1Y/3jPFN3D2xNBUOu14eW6zLF8YQsMVfUTDJkjWEnnQkrnPZHCpatHnwvLpUL4BycSwMjew/G+067K0ZwY35gxlO02JhL42WPmWVfAuWllLt7LtOzj50YZCU+0IqYd7Dhe3LdB/PsDSkyER+N7dWNhJ0l+RwgQFG4LDFwStFCSn6/v1pWw5Q8zqq3pl98B+qPemdmIYyQFh7vLRnCJY2UOOPo3NLdBO42yWaYaxDtSPxqIeMocIeounjCFpboubVzNwR558msxehg2EmeqYQBmba1U6ktjwBXq+w2BXOqkz1zMSdybtqS949s26rlWQoX5bhoqX01m66y+A5j0mF4rZsuqiF7HPHbXjE+DcRePXveMqC8pPmjCc=
  app: fast-brushlands-35777
  on:
    repo: lightsage88/gdc2Client
  skip_cleanup: 'true'
env:
  global:
    secure: PVo13y0rfonXYUv7pX9la1A69UJ91/zJ9BVidQelK0vgokY5My0tq655RFh15LMZkwKuidn9LJtPEiVf8geQqslP5gmJgk8z+9MtRhyGkaup0awANNM0C0e1hgFAE4ucdXe5AikLGJbgxOtD0wB4kfp8fm4JD9TV0KEnR+LMIBG753RvU2p1DI5WQRrMCHN+jp/EkM04bc/0HlbLOE+CYCTzXlUBur+Q1ILqM3jKQdgVy7QGDY8wjp4okGOcvJaxzjixZ10V59NV4fbRLi/vhvbhCu0SLMGKWrKxnUPhZwSV2ZjvmtD/elLeqWxeS47yqNrLAnYHDIKWfP3FT18jkE9pZSOundC2LaH7+e3cFDDvIcOeC4PBEh6nMnA1IIAiyX/XCINaZRNr/RFPD+/hBSoK04OloaRPDfZN6GGGiLbq78TOGsGRwuWPNw4zCsY1RHOJdEerI3Amgya2+aaRjGFiS5eZuEWAR6D/6oG4M9l8aK4ZasaNBt01L+25b8x48tuWdbdhSbBpgOu1r/tGrtcWqn2VHlVS9ZU0h5I4ZraZTTs4vJDEt44LT+fLCWKEKfnurNVy3evc9K5SVPEkZ9ksGa1jbRV6knSuc22WYzBbv2EN67LyNmdupwqf2szNsr57rU4ARZGwtd5VcOzCUGMO/9/phHtgx17eH7AuOBE=
