dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  chrome: stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
- npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
deploy:
  provider: heroku
  api_key:
    secure: 72b5fa63-feab-44ff-9bbe-a89a63393855
  app: fast-brushlands-35777
  on:
    repo: lightsage88/gdc2Client
