dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  chrome: stable
  chromedriver: "./node_modules/protractor/bin/webdriver-manager update --versions.chrome=84.0.4147.30"
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  provider: heroku
  api_key:
    secure: lvppXLjfr1jiV9EhNDYFxgW6ewU4n8Qe0dM96eQNdfR8DzySn8J+WZlolWsaRfHBDPwqXT9/HGdZ/E4Wcg5gOtTvE4fUMbDwvJbWcXVbXAUT9bUh2sH298VW83w9Z+URgYmCQoScaBd3kkZUIuI4btFp7u10/nQxVIoPlrMOZpzGZ1LYVs3jxPCC1iNFdrTJt38eZH6HxgEGNgQXgYK6slcB9YBQbog8KLzlwCxBgck6WgIK6VZBj4PLBL7bR5aoHUapSE9RsYUIgrlNpDOiqGG2mqTmBgJryOL2FHUUlYaonaSBOsLGxIPo2AiHz6O6Q6erK272zhsEnDgC6CNN08uz6pEBaW19qJcunRwQCqibH+dX2v0kg8767PxuRwvBh9yoXIqVo3rLcCZLK8yoxiXXy8VJo3V+CgNGTR9sMxRD7+Q+LghjwkusRNDeAuVloOBTqYCgAs7mngz+v85VDymk+XUWTQF3cz6c31Yq5KiXx5zScOWsLWZAoTSCFAG7v4al6t5DkZDkube8uis2aLTUtoGwoEvMK0y1nKUB9giOwgwFdUKf6v10Y/TQhEuTkqa/Gg1qcsmQHNVZjhqB9cWTkx6BplCk4w1rxTfSkxHDU9cuUoLlK26i1cp4gNWIU7XYgNeGarsb8pM/qsWReALiEi7deHx8q0DttdDqeVY=
  app: fast-brushlands-35777
  on:
    repo: lightsage88/gdc2Client
  skip_cleanup: 'true'
env:
  global:
    secure: PVo13y0rfonXYUv7pX9la1A69UJ91/zJ9BVidQelK0vgokY5My0tq655RFh15LMZkwKuidn9LJtPEiVf8geQqslP5gmJgk8z+9MtRhyGkaup0awANNM0C0e1hgFAE4ucdXe5AikLGJbgxOtD0wB4kfp8fm4JD9TV0KEnR+LMIBG753RvU2p1DI5WQRrMCHN+jp/EkM04bc/0HlbLOE+CYCTzXlUBur+Q1ILqM3jKQdgVy7QGDY8wjp4okGOcvJaxzjixZ10V59NV4fbRLi/vhvbhCu0SLMGKWrKxnUPhZwSV2ZjvmtD/elLeqWxeS47yqNrLAnYHDIKWfP3FT18jkE9pZSOundC2LaH7+e3cFDDvIcOeC4PBEh6nMnA1IIAiyX/XCINaZRNr/RFPD+/hBSoK04OloaRPDfZN6GGGiLbq78TOGsGRwuWPNw4zCsY1RHOJdEerI3Amgya2+aaRjGFiS5eZuEWAR6D/6oG4M9l8aK4ZasaNBt01L+25b8x48tuWdbdhSbBpgOu1r/tGrtcWqn2VHlVS9ZU0h5I4ZraZTTs4vJDEt44LT+fLCWKEKfnurNVy3evc9K5SVPEkZ9ksGa1jbRV6knSuc22WYzBbv2EN67LyNmdupwqf2szNsr57rU4ARZGwtd5VcOzCUGMO/9/phHtgx17eH7AuOBE=
