dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  chrome: stable
  chromedriver: "./node_modules/protractor/bin/webdriver-manager update --versions.chrome=84.0.4147.30"
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  provider: heroku
  api_key:
    secure: X7tGh9hxIGqYoS9FaWGEmnE2mI7mn/HRKwAwl91QJDAwQbxIqUsLi9mMHUDh44FXkYuvflFExi0a10lMJHCVOC17HybtTd9QlXk9jLm9eGOXX/6+GCbJUfpQBHM5Nb6e7K4g8a7prTu54YVw5M0UBqLkc1hrpEDhXT8vuF7ho+ayKITD2LNs48jlqq6VQxVFxS52HuhDZcFwCy+26ENJ8WjJDA8UqZsNdCjf7znYsrw+4FcSEN672DKnBUtRhz93tg5XIed7Z7jx4gLDTs/PbLwbIPL92JUCYWey7KtRLVaqnI3rGlPDBlDchQmz1P1EGxQdpZ+OoIlqfqCDZ4oYdKUg0eUL543GBbPt80ut2kYFq3IdonzmDSc2cOAGvKX1tNCJy3qvDaIi5ltppaSnOgDs7paTGfYw0WWHwXmO7ksXLiE5HFsVA0ZIElKS05TccrVuiTv9k4nBC+7+O5qNUCF9AuxdUJQQuWu6PGunX3OiRxMM15du7EPDLIikDAhbfZ6nWX9M2L/FI5lMiYt4i9eA0C5uUacaWAFsWS/T8PS2OZzV8z2q/E9YrBWXbK7gBmhRgCgaT91qBTRxo1eQbs/c91qdYYZgD9l6dlHmjcXQusFNBAEWlNbq1+GXUWrKX8oHqjH1auxYqeUV/WlbB+YEwOOkPqQcBeyQHwY0cIw=
  app: fast-brushlands-35777
  on:
    repo: lightsage88/gdc2Client
