dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  chrome: stable
  chromedriver: "./node_modules/protractor/bin/webdriver-manager update --versions.chrome=84.0.4147.30"
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  provider: heroku
  api_key:
    secure: UADc8YP7VJKwTeOeI+xdH15Ec/sfqtx4p/K2vqadj1Z7Hydh0mrmF8f0OgnU8Hur6EaEnguvC7yFSUBq+dcVNqdedrukq7Bovuts8WMalqN3Ds16jNib2G1VU3caV4hXRL/7dfZu9LyHFE7h4sx1DaS0yqbLKQR46IGdAHA71KCnFWuyswkns7Lxpp4wmouQt5yN89ZJzkvcInh3PSJEH+kQzaWniYBRSmiKlENN8IyN5zBqaCT/bgsnQa13ETDEx39IuzxcpNzWQiHEllwoPigzSSvyfzp6Zr0w8WNtFS4xQa3GhSqixcn+Lqy39gKuiQnvDOhyqVcIMGU05KpdZxB/xyax+qWfDSckkHN5WuACLpFdu26tMiTT+yg2X1zqcf2+rEhxjpltW1ALXThGYnCHQCZA0tGxdqaeyRWHhlBrxPG2nHCOTL/3NDw0CH5Eq2mloqoJm4xq7lD/62KSsRnfRmdar3ypzmnLxSygcOw8kmWZ0zVLtZDec8JgSqqDMV1rKNqYrvM0BwszFJvPL8r/xiBkwWbdkZNuqsV6o3tG5cxfC4Hs2/vz3mK44PT3ML/aiCZAJNzfyKywYU5xALEnWC+FF7rEvA3jAzbbp3fyjO/4nkdU92/v8XFj/DipQo/bC+TCYSgnQ05TcYRYNmLW244tp0ggB4UY8UtssMU=
  app: fast-brushlands-35777
  on:
    repo: lightsage88/gdc2Client
